# Week 04: BoardGames

Inspired by
https://github.com/jvieroe/TidyTuesday/blob/main/2022/week_04/code_boardgames.R

And

https://github.com/leeolney3/TidyTuesday/blob/main/2022/week_04/2022_04.R

### 1.0 Load packages and data
```{r R-packages}
library(tidytuesdayR)
library(tidyverse)
library(janitor)
library(showtext)
library(reticulate)
library(glue)
library(patchwork)


# ============================================================================ #
# Read Data
# ============================================================================ #

# TidyTuesday Load
df <- tidytuesdayR::tt_load(2022, week = 4)

# data frame both tibbles
ratings <- df$ratings %>%
    janitor::clean_names()

details <- df$details %>%
    janitor::clean_names()

# Join by id
df <- ratings %>%
    left_join(details, by = "id")
```

### 2.0 Data Wrangling
```{r dataCleansing}
# ============================================================================ #
# Best High-Worse Rated board games from 1 to 4 players (Max)

# What about bayes average?
# https://en.wikipedia.org/wiki/Bayesian_average

# Names data
df_players <- df %>%
    select(
        name,
        users_rated,
        average,
        bayes_average,
        maxplayers
    ) %>%
    group_by(maxplayers) %>%
    filter(average == min(average) | average == max(average)) %>%
    filter(maxplayers <= 4 & maxplayers != 0) %>%
    arrange(maxplayers, average) %>%
    ungroup()
```

### 3.0 Using Python
```{python iterator}
# How to Create a column with repeating values pandas (mismatching indexes)
# https://stackoverflow.com/questions/50804427/how-to-create-a-column-with-repeating-values-pandas-mismatching-indexes

# Importing from R
df = r.df_players
all_data = r.df

# Repeating section
lista = ["Worst", "Best"]
list_iterator = lista * int(len(df)/len(lista))
df["best_worst"] = list_iterator

all_data.users_rated.mean()
all_data.users_rated.median()
all_data.users_rated.max()
all_data.users_rated.describe()
```

### 4.0 Back to R - Pivot longer
```{r pivotLonger}
# Adding data from Python
df_players <- py$df %>%
    as_tibble()

# Format data
df_players <- df_players  %>%
    relocate(name, best_worst, maxplayers, everything()) %>%
    mutate(
        maxplayers = as_factor(maxplayers),
        name = as_factor(name)
    ) %>%
    pivot_longer(
        cols = average:bayes_average,
        names_to = "type",
        values_to = "value"
    )

# Filter best and worst data frames
df_best <- df_players %>%
    filter(best_worst == "Best")

df_worst <- df_players %>%
    filter(best_worst == "Worst")
```


### Bar Plot for both data sets
```{r barPlots}
# ============================================================================ #
# Best Rated games

df_best %>%
    rename(Rating = type)  %>%
    # ggplot
    ggplot(aes(x = name, y = value, fill = Rating)) +
    # geoms
    geom_col(position = position_dodge(0.7), width = 0.3, alpha = 0.8) +
    facet_wrap(
        vars(
            name,
            glue(
                "# users_rated: {users_rated} | # max players: {maxplayers}")
        ),
        nrow = 2,
        scales = "free_x"
    ) +
    scale_fill_manual(values = c(
        "#58ecf1",
        "#12b16f"
    )) +
    scale_y_continuous(
        limits = c(0, 10),
        breaks = c(0, 4, 8)
    ) +
# labs
# https://fulmicoton.com/posts/bayesian_rating/
    labs(
    x = "",
    y = "Average Rating\n",
    title = "Best Board Games by Rating\n",
    caption = "@valdezdata | #TidyTuesday W04 | Kaggle Board Games Geek"
    ) +
# theme
    theme(
        text = element_text(family = "Montserrat"),
        rect = element_rect(fill = "#cee9ff"),
        plot.background = element_rect(fill = "#cee9ff", color = NA),
        panel.background = element_rect(fill = "#cee9ff", color = NA),
        panel.border = element_blank(),
        legend.position = "bottom",
        plot.caption = element_text(size = 10),
        plot.title = element_text(
            face = "bold",
            size = 20,
            hjust = 0.5,
            color = "#086460"
            ),
        plot.subtitle = element_text(size = 12, hjust = 0.5),
        panel.grid.major.y = element_line(color = "grey75"),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(color = "grey75"),
        panel.grid.minor.x = element_blank(),
        axis.text.y = element_text(face = "italic", size = 12),
        axis.text.x = element_blank(),
        axis.title.y = element_text(face = "bold", vjust = 1),
        axis.title.x = element_text(face = "bold", vjust = -0.1),
        strip.background = element_rect(
            fill = "#b8e3ff"
        ),
        strip.text.x = element_text(face = "bold", size = 10)
    )

# --- ggsave ---
ggsave("2022/W04_BoardGames/best_boardgames_rating.png")

# ============================================================================ #
# Worst Rated games

df_worst %>%
    rename(Rating = type)  %>%
    # ggplot
    ggplot(aes(x = name, y = value, fill = Rating)) +
    # geoms
    geom_col(position = position_dodge(0.7), width = 0.3, alpha = 0.8) +
    facet_wrap(
        vars(
            name,
            glue(
                "# users_rated: {users_rated} | # max players: {maxplayers}")
        ),
        nrow = 2,
        scales = "free_x"
    ) +
    scale_fill_manual(values = c(
        "#b96d16",
        "#6e4225ab"
    )) +
    scale_y_continuous(
        limits = c(0, 10),
        breaks = c(0, 4, 8)
    ) +
# labs
# https://fulmicoton.com/posts/bayesian_rating/
    labs(
    x = "",
    y = "Average Rating\n",
    title = "Worst Board Games by Rating\n",
    caption = "@valdezdata | #TidyTuesday W04 | Kaggle Board Games Geek"
    ) +
# theme
    theme(
        text = element_text(family = "Montserrat"),
        rect = element_rect(fill = "#ffd5ce"),
        plot.background = element_rect(fill = "#ffd5ce", color = NA),
        panel.background = element_rect(fill = "#ffd5ce", color = NA),
        panel.border = element_blank(),
        legend.position = "bottom",
        plot.caption = element_text(size = 10),
        plot.title = element_text(
            face = "bold",
            size = 20,
            hjust = 0.5,
            color = "#200446"
            ),
        plot.subtitle = element_text(size = 12, hjust = 0.5),
        panel.grid.major.y = element_line(color = "grey75"),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_line(color = "grey75"),
        panel.grid.minor.x = element_blank(),
        axis.text.y = element_text(face = "italic", size = 12),
        axis.text.x = element_blank(),
        axis.title.y = element_text(face = "bold", vjust = 1),
        axis.title.x = element_text(face = "bold", vjust = -0.1),
        strip.background = element_rect(
            fill = "#ffc1b5"
        ),
        strip.text.x = element_text(face = "bold", size = 10)
    )

# --- ggsave ---
ggsave("2022/W04_BoardGames/worst_boardgames_rating.png",
    width = 7, height = 4.8
)
```

### END